language: python
python:
 - "3.5"
 - "3.6" # current default Python on Travis CI
 - "3.7"
 - "3.8"
# command to install dependencies
install:
 - pip install -r requirements.txt
# doxygen package
addons:
  apt:
    packages:
      - doxygen
# command to run tests and doxygen
script:
 - python tests/test.py
 - python tests/test_digits.py
 - if [ "$TRAVIS_BRANCH" = "tests_preparations" ]; then doxygen Doxyfile; fi
# documentation deployment
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: tests_preparations